### ISSUE TITLE
合作

### ISSUE THREAD

**Issue by fengxiuyaun** [YiyangHuang-work/RT-1#1]
目前我们正在做具身智能方面的研究，有机会合作一下吗？来我们这实习或工作

**Comment by hyy02** [comment]
可以的，我们也很希望跟公司合作，你可以添加我的微信15663621700



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月20日(周五) 中午11:14
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [YiyangHuang-work/RT-1] 合作 (Issue #1)




 
目前我们正在做具身智能方面的研究，有机会合作一下吗？来我们这实习或工作
