### ISSUE TITLE
RUN rlds_np_save.py can't transfer dict to numpy.

### ISSUE THREAD

**Issue by lin-whale** [YiyangHuang-work/RT-1#2]
hello! thanks for your contribution and sharing!
I met a problem when I try to do data processing according your code, just run rlds_np_save.py in language_table_data_reconstruction. The error is:

`Traceback (most recent call last):
  File "rlds_np_save.py", line 54, in <module>
    create_episode(f'{des_dataset}/train/episode_{cnt}.npy',element)
  File "rlds_np_save.py", line 35, in create_episode
    step_dict[k] = step[k].numpy()
AttributeError: 'dict' object has no attribute 'numpy'`

So I scan the data format. I found that the content in step[k] contains simple tuple most. 
But for step['action'], it contains dict so can't be transfered by ".numpy()" directly. Like following instence.
 So I want to know how to tackle this issue?

_('reward', <tf.Tensor: shape=(), dtype=float32, numpy=0.0>)
('action', {'rotation_delta': <tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.        , 0.        , 0.40559822], dtype=float32)>, 'terminate_episode': <tf.Tensor: shape=(), dtype=float32, numpy=0.0>, 'world_vector': <tf.Tensor: shape=(3,), dtype=float32, numpy=array([-0.09170523,  0.08510224,  0.16813292], dtype=float32)>})
('is_first', <tf.Tensor: shape=(), dtype=bool, numpy=False>)
('is_last', <tf.Tensor: shape=(), dtype=bool, numpy=False>)
('is_terminal', <tf.Tensor: shape=(), dtype=bool, numpy=False>)
('observation', {'image': <tf.Tensor: shape=(128, 128, 3), dtype=uint8, numpy=
array([[[ 61,  69,  71],
        [ 56,  62,  65],
        [ 65,  69,  72],
        ...,_

**Comment by lin-whale** [comment]
I figure the problem...
Because diffent datasets in RT-X have different format...
For language table set as following, the code should work.


`<class_` 'tuple'>
('reward', <tf.Tensor: shape=(), dtype=float32, numpy=1.0>)
<class 'tuple'>
('action', <tf.Tensor: shape=(2,), dtype=float32, numpy=array([0., 0.], dtype=float32)>)
<class 'tuple'>
('is_first', <tf.Tensor: shape=(), dtype=bool, numpy=False>)
<class 'tuple'>
('is_last', <tf.Tensor: shape=(), dtype=bool, numpy=True>)
<class 'tuple'>
('is_terminal', <tf.Tensor: shape=(), dtype=bool, numpy=False>)
<class 'tuple'>
('observation', {'effector_target_translation': <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.29155338, -0.18629198], dtype=float32)>, 'effector_translation': <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.291708  , -0.18574017], dtype=float32)>, 'instruction': <tf.Tensor: shape=(512,), dtype=int32, numpy=
array([109, 111, 118, 101,  32,  98, 108, 117, 101,  32, 116, 114, 105,
        97, 110, 103, 108, 101,  32, 116, 111, 119,  97, 114, 100, 115,
        32, 116, 104, 101,  32, 116, 111, 112,  32, 108, 101, 102, 116,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,`

**Comment by hyy02** [comment]
Yes, you are right. Since the author of the RT-1 article did not plan to disclose the simulation environment for the time being, I used the language-table dataset, which has some minor differences between them. Now I recommend you to do the same.If there is a simulation environment of RT-1 in the future, I will modify the project code.
