### ISSUE TITLE
how to train this model on custom datasets

### ISSUE THREAD

**Issue by hualala00** [YiyangHuang-work/RT-1#7]
Thank for your work first.
I am a beginner and I don't know how to train this model on custom dataset. could you provide more details?I will appreciate for it!

**Comment by hyy02** [comment]
Sorry,  I just saw this question. For the custom dataset, I highly recommend you to see this[ repository ](https://github.com/kpertsch/rlds_dataset_builder)or the folder [language_table_data_reconstruction](https://github.com/hyy0613/RT-1/tree/main/language_table_data_reconstruction) in this repository; it gives you the tutorial for changing your custom dataset to [rlds](https://github.com/google-research/rlds) type, then you can change several codes and efficiently use the RT-1 model given by Google. You should also evaluate your GPU resources. RT-1 is a classic model suitable for getting started, but it is no longer SOTA; this project requires a 32G GPU. If you have a better GPU, I also recommend that you try other models that have better performance.
